name: demo checks

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Version to deploy'
    #     required: true
    #     type: string
    #     default: 0



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version from Git reference
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's#refs/tags/##; s#refs/heads/[^-]*-##')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  # Сохраняем VERSION в GITHUB_ENV

      # - name: count pr
      #   run: |
      #     OPEN_PR_COUNT=$(curl -L -H "Accept: application/vnd.github+json" \
      #                     -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
      #                     -H "X-GitHub-Api-Version: 2022-11-28" \
      #                     "https://api.github.com/repos/${{ github.repository }}/pulls?head=DavidOhanyan:${{ github.ref_name }}&state=open" | jq 'length')

      #     echo "count of pr $OPEN_PR_COUNT"
      #     echo "branch version APT-${{ env.VERSION }}"
          
      #     if [ "$OPEN_PR_COUNT" -gt 0 ]; then
      #       echo "Ошибка: Есть открытые PR!"
      #       echo "Смотри детали workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #       exit 1
      #     fi
          
      - name: check aktualnost vetki
        run: |
          BEHIND_COUNT=$(curl -L   -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/compare/main...${{ github.ref_name }} | jq '.behind_by')

          echo "kalichestvo rovno $BEHIND_COUNT"
          if [ "$BEHIND_COUNT" -gt 0 ]; then
            echo "Ошибка: vetka ne aktualnaya"
            echo "Смотри детали workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            exit 1
          fi
  
