on:
  workflow_dispatch:

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: 1.4.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
