name: Delayed Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Какой-то параметр"
        required: true
        type: string



jobs:
  show-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print repo name
        run: echo "Repository name is $GITHUB_REPOSITORY"
