name: Delayed Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Какой-то параметр"
        required: true
        type: string

jobs:
  delayed-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: dsda
        run: | 
          echo vot nasha versya ${{ github.event.inputs.version }}
          cat aaaaa
