name: PROD.DEPLOY

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: 0

concurrency:
  group: ${{ github.ref_name }}

env:
    BUILD_BRANCH: ${{ github.ref }}
    REPO_URL: europe-central2-docker.pkg.dev/keyprofi/avitrage/emaki_api
    APP_VERSION: ${{ github.event.inputs.version }}
    HELM_CHART_NAME: emaki-api-prod-chart-${{ github.event.inputs.version }}
    NAMESPACE: emaki-api
    TRIGGERED_BY: ${{ github.event.inputs.initiator }}

jobs:
  extract-and-use:
    runs-on: ubuntu-latest

    steps:
      - name: Get number from branch name and export to GITHUB_ENV
        run: |
          NUMBER=$(echo "${GITHUB_REF_NAME}" | grep -o '[0-9]\+')
          echo "CLEAN_VERSION=$NUMBER" >> $GITHUB_ENV

      - name: Use extracted number
        run: echo "Clean version is: $CLEAN_VERSION"
