name: Delayed Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Какой-то параметр"
        required: true
        type: string



jobs:
  extract-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repo name only
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo "Repo name: $REPO_NAME"
