name: Delayed Hello World

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: 0

      silent:
        description: 'Отправить сообщение без звука?'
        required: true
        type: choice
        default: "true"
        options:
          - "true"
          - "false"




jobs:
  extract-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repo name only
        run: |
          echo ${{ github.event.inputs.version }}
          echo '${{ github.event.inputs.version }}'
