name: PROD.DEPLOY

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: 0

concurrency:
  group: ${{ github.ref_name }}

env:
    BUILD_BRANCH: ${{ github.ref }}
    REPO_URL: europe-central2-docker.pkg.dev/keyprofi/avitrage/emaki_api
    APP_VERSION: ${{ github.event.inputs.version }}
    HELM_CHART_NAME: emaki-api-prod-chart-${{ github.event.inputs.version }}
    NAMESPACE: emaki-api
    TRIGGERED_BY: ${{ github.event.inputs.initiator }}

jobs:
    deploy-prod:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout the code from repo
          run: |
              echo "${GITHUB_REF_NAME}"
